namespace Microsoft.Diagnostics.Runtime;

internal enum PSS_QUERY_INFORMATION_CLASS
{
	PSS_QUERY_PROCESS_INFORMATION,
	PSS_QUERY_VA_CLONE_INFORMATION,
	PSS_QUERY_AUXILIARY_PAGES_INFORMATION,
	PSS_QUERY_VA_SPACE_INFORMATION,
	PSS_QUERY_HANDLE_INFORMATION,
	PSS_QUERY_THREAD_INFORMATION,
	PSS_QUERY_HANDLE_TRACE_INFORMATION,
	PSS_QUERY_PERFORMANCE_COUNTERS
}
