namespace Microsoft.Diagnostics.Runtime.ICorDebug;

public enum CorDebugChainReason
{
	CHAIN_CLASS_INIT = 1,
	CHAIN_CONTEXT_POLICY = 8,
	CHAIN_CONTEXT_SWITCH = 1024,
	CHAIN_DEBUGGER_EVAL = 512,
	CHAIN_ENTER_MANAGED = 128,
	CHAIN_ENTER_UNMANAGED = 256,
	CHAIN_EXCEPTION_FILTER = 2,
	CHAIN_FUNC_EVAL = 2048,
	CHAIN_INTERCEPTION = 16,
	CHAIN_NONE = 0,
	CHAIN_PROCESS_START = 32,
	CHAIN_SECURITY = 4,
	CHAIN_THREAD_START = 64
}
