using System;

namespace Microsoft.Diagnostics.Runtime.Interop;

[Flags]
public enum DEBUG_ENGOPT : uint
{
	NONE = 0u,
	IGNORE_DBGHELP_VERSION = 1u,
	IGNORE_EXTENSION_VERSIONS = 2u,
	ALLOW_NETWORK_PATHS = 4u,
	DISALLOW_NETWORK_PATHS = 8u,
	NETWORK_PATHS = 0xCu,
	IGNORE_LOADER_EXCEPTIONS = 0x10u,
	INITIAL_BREAK = 0x20u,
	INITIAL_MODULE_BREAK = 0x40u,
	FINAL_BREAK = 0x80u,
	NO_EXECUTE_REPEAT = 0x100u,
	FAIL_INCOMPLETE_INFORMATION = 0x200u,
	ALLOW_READ_ONLY_BREAKPOINTS = 0x400u,
	SYNCHRONIZE_BREAKPOINTS = 0x800u,
	DISALLOW_SHELL_COMMANDS = 0x1000u,
	KD_QUIET_MODE = 0x2000u,
	DISABLE_MANAGED_SUPPORT = 0x4000u,
	DISABLE_MODULE_SYMBOL_LOAD = 0x8000u,
	DISABLE_EXECUTION_COMMANDS = 0x10000u,
	DISALLOW_IMAGE_FILE_MAPPING = 0x20000u,
	PREFER_DML = 0x40000u,
	ALL = 0x7FFFFu
}
