namespace DebugDiag.DbgEng;

public enum DEBUG_FILTER : uint
{
	CREATE_THREAD = 0u,
	EXIT_THREAD = 1u,
	CREATE_PROCESS = 2u,
	EXIT_PROCESS = 3u,
	LOAD_MODULE = 4u,
	UNLOAD_MODULE = 5u,
	SYSTEM_ERROR = 6u,
	INITIAL_BREAKPOINT = 7u,
	INITIAL_MODULE_LOAD = 8u,
	DEBUGGEE_OUTPUT = 9u,
	BREAK = 0u,
	SECOND_CHANCE_BREAK = 1u,
	OUTPUT = 2u,
	IGNORE = 3u,
	REMOVE = 4u,
	GO_HANDLED = 0u,
	GO_NOT_HANDLED = 1u
}
