using System;

namespace DebugDiag.DbgEng;

[Flags]
public enum DEBUG_STACK : uint
{
	ARGUMENTS = 1u,
	FUNCTION_INFO = 2u,
	SOURCE_LINE = 4u,
	FRAME_ADDRESSES = 8u,
	COLUMN_NAMES = 0x10u,
	NONVOLATILE_REGISTERS = 0x20u,
	FRAME_NUMBERS = 0x40u,
	PARAMETERS = 0x80u,
	FRAME_ADDRESSES_RA_ONLY = 0x100u,
	FRAME_MEMORY_USAGE = 0x200u,
	PARAMETERS_NEWLINE = 0x400u,
	DML = 0x800u,
	FRAME_OFFSETS = 0x1000u
}
