using System;

namespace DebugDiag.DbgEng;

[Flags]
public enum DEBUG_ATTACH : uint
{
	KERNEL_CONNECTION = 0u,
	LOCAL_KERNEL = 1u,
	EXDI_DRIVER = 2u,
	NONINVASIVE = 1u,
	EXISTING = 2u,
	NONINVASIVE_NO_SUSPEND = 4u,
	INVASIVE_NO_INITIAL_BREAK = 8u,
	INVASIVE_RESUME_PROCESS = 0x10u,
	NONINVASIVE_ALLOW_PARTIAL = 0x20u
}
