using System;

namespace Microsoft.Diagnostics.Runtime.Interop;

[Flags]
public enum DEBUG_CES : uint
{
	ALL = uint.MaxValue,
	CURRENT_THREAD = 1u,
	EFFECTIVE_PROCESSOR = 2u,
	BREAKPOINTS = 4u,
	CODE_LEVEL = 8u,
	EXECUTION_STATUS = 0x10u,
	ENGINE_OPTIONS = 0x20u,
	LOG_FILE = 0x40u,
	RADIX = 0x80u,
	EVENT_FILTERS = 0x100u,
	PROCESS_OPTIONS = 0x200u,
	EXTENSIONS = 0x400u,
	SYSTEMS = 0x800u,
	ASSEMBLY_OPTIONS = 0x1000u,
	EXPRESSION_SYNTAX = 0x2000u,
	TEXT_REPLACEMENTS = 0x4000u
}
