namespace Microsoft.Diagnostics.Runtime.Interop;

public enum DEBUG_FILTER_EVENT : uint
{
	CREATE_THREAD,
	EXIT_THREAD,
	CREATE_PROCESS,
	EXIT_PROCESS,
	LOAD_MODULE,
	UNLOAD_MODULE,
	SYSTEM_ERROR,
	INITIAL_BREAKPOINT,
	INITIAL_MODULE_LOAD,
	DEBUGGEE_OUTPUT
}
