namespace Microsoft.Diagnostics.Runtime.Interop;

public enum DEBUG_HANDLE_DATA_TYPE : uint
{
	BASIC,
	TYPE_NAME,
	OBJECT_NAME,
	HANDLE_COUNT,
	TYPE_NAME_WIDE,
	OBJECT_NAME_WIDE,
	MINI_THREAD_1,
	MINI_MUTANT_1,
	MINI_MUTANT_2,
	PER_HANDLE_OPERATIONS,
	ALL_HANDLE_OPERATIONS,
	MINI_PROCESS_1,
	MINI_PROCESS_2
}
