using System;

namespace Microsoft.Diagnostics.Runtime.Interop;

[Flags]
public enum DEBUG_CDS_REFRESH : uint
{
	EVALUATE = 1u,
	EXECUTE = 2u,
	EXECUTECOMMANDFILE = 3u,
	ADDBREAKPOINT = 4u,
	REMOVEBREAKPOINT = 5u,
	WRITEVIRTUAL = 6u,
	WRITEVIRTUALUNCACHED = 7u,
	WRITEPHYSICAL = 8u,
	WRITEPHYSICAL2 = 9u,
	SETVALUE = 0xAu,
	SETVALUE2 = 0xBu,
	SETSCOPE = 0xCu,
	SETSCOPEFRAMEBYINDEX = 0xDu,
	SETSCOPEFROMJITDEBUGINFO = 0xEu,
	SETSCOPEFROMSTOREDEVENT = 0xFu,
	INLINESTEP = 0x10u,
	INLINESTEP_PSEUDO = 0x11u
}
