namespace DebugDiag.AnalysisRules;

public class SequenceGraph
{
	public void DrawGraph()
	{
		Globals.Manager.Write("<br>");
		Globals.Manager.Write("<br>");
		Globals.Manager.Write("<table id=\"Table1\" style=\"BORDER-RIGHT: black thin solid; BORDER-TOP: black thin solid; BORDER-LEFT: black thin solid; BORDER-BOTTOM: black thin solid\" cellspacing=\"1\" cellpadding=\"1\" width=\"100%\" border=\"0\" class=myCustomText>");
		Globals.Manager.Write("<tbody>");
		Globals.Manager.Write("<tr height=\"30\">");
		Globals.Manager.Write("<td width=\"30\"></td>");
		Globals.Manager.Write("<td align=\"middle\"><br>");
		Globals.Manager.Write("<h4>Operation Map</h4>");
		Globals.Manager.Write("</td>");
		Globals.Manager.Write("<td width=\"30\"></td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td width=\"30\"></td>");
		Globals.Manager.Write("<td>");
		Globals.Manager.Write("<table id=\"Table2\" style=\"BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: none\" cellspacing=\"1\" cellpadding=\"4\" width=\"100%\" border=\"0\" class=myCustomText>");
		Globals.Manager.Write("<tbody>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td nowrap=\"\" align=\"middle\" colspan=\"2\">Dump 1</td>");
		Globals.Manager.Write("<td width=\"75%\"></td>");
		Globals.Manager.Write("<td nowrap=\"\" align=\"middle\" colspan=\"2\">Dump 2</td>");
		Globals.Manager.Write("<td width=\"25%\"></td>");
		Globals.Manager.Write("<td nowrap=\"\" align=\"middle\" colspan=\"2\">Dump 3</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr height=\"5\">");
		Globals.Manager.Write("<td width=\"10\"></td>");
		Globals.Manager.Write("<td width=\"10\"></td>");
		Globals.Manager.Write("<td width=\"75%\"></td>");
		Globals.Manager.Write("<td width=\"10\"></td>");
		Globals.Manager.Write("<td width=\"10\"></td>");
		Globals.Manager.Write("<td width=\"25%\"></td>");
		Globals.Manager.Write("<td width=\"10\"></td>");
		Globals.Manager.Write("<td width=\"10\"></td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td style=\"WIDTH: 10px\"></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted; WIDTH: 10px\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"WIDTH: 10px\"></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted; WIDTH: 10px\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"WIDTH: 10px\"></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted; WIDTH: 10px\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td style=\"BORDER-RIGHT: black 1px solid; BORDER-TOP: black 1px solid; BORDER-LEFT: black 1px solid; BORDER-BOTTOM: black 1px solid; HEIGHT: 29px\" align=\"middle\" bgcolor=\"lemonchiffon\" colspan=\"8\">");
		Globals.Manager.Write("<img src=\"res\\cpu.png\">&nbsp;<img src=\"res\\asp.png\">&nbsp;&nbsp;spin.asp</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td style=\"BORDER-RIGHT: black 1px solid; BORDER-TOP: black 1px solid; BORDER-LEFT: black 1px solid; BORDER-BOTTOM: black 1px solid; HEIGHT: 29px\" align=\"middle\" bgcolor=\"aliceblue\" colspan=\"8\">");
		Globals.Manager.Write("<img src=\"res\\asp.png\">&nbsp;slow.asp</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr style=\"FONT-SIZE: xx-small\">");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td style=\"BORDER-RIGHT: black 1px solid; BORDER-TOP: black 1px solid; BORDER-LEFT: black 1px solid; BORDER-BOTTOM: black 1px solid; HEIGHT: 29px\" align=\"middle\" bgcolor=\"aliceblue\" colspan=\"8\">");
		Globals.Manager.Write("<img src=\"res\\asp.png\">&nbsp;slow.asp</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr style=\"FONT-SIZE: xx-small\">");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-RIGHT: black 1px solid; BORDER-TOP: black 1px solid; BORDER-LEFT: black 1px solid; BORDER-BOTTOM: black 1px solid; HEIGHT: 29px\" align=\"middle\" bgcolor=\"aliceblue\" colspan=\"5\">");
		Globals.Manager.Write("<img src=\"res\\asp.png\">&nbsp;foo.asp</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td style=\"BORDER-RIGHT: black 1px solid; BORDER-TOP: black 1px solid; BORDER-LEFT: black 1px solid; BORDER-BOTTOM: black 1px solid; HEIGHT: 29px\" align=\"middle\" bgcolor=\"aliceblue\" colspan=\"2\">");
		Globals.Manager.Write("<img src=\"res\\asp.png\">&nbsp;foo.asp</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td style=\"BORDER-LEFT: gray thin dotted\">&nbsp;</td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("</tbody>");
		Globals.Manager.Write("</table>");
		Globals.Manager.Write("</td>");
		Globals.Manager.Write("<td width=\"30\"></td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr height=\"30\">");
		Globals.Manager.Write("<td width=\"30\"></td>");
		Globals.Manager.Write("<td></td>");
		Globals.Manager.Write("<td width=\"30\"></td>");
		Globals.Manager.Write("</tr>");
		Globals.Manager.Write("<tr><td colspan=\"3\" align=\"center\">(sample data)</td></tr>");
		Globals.Manager.Write("</tbody>");
		Globals.Manager.Write("</table>");
		Globals.Manager.Write("<br>");
		Globals.Manager.Write("<br>");
	}
}
